### ISSUE TITLE
maybe include simple SVG HOWTO?

### ISSUE THREAD

**Issue by aspiers** [fghaas/presentation-template#16]
Feel free to steal (ideas from) https://github.com/aspiers/presentation-template/commit/1d66aca23775f5dbe9fcadae5909cdb3b3d6fccc if you think it's worthwhile, or simply ignore and close this :-)

**Comment by fghaas** [comment]
Hmm. Well there's tons of options that people have to include SVG. What comes to mind is
- SVG export from Dia
- SVG export from Google Drawings
- http://www.drawsvg.org/
- http://editor.method.ac/
- Inkscape
- probably others that I'm not thinking of right now.

Thanks for the suggestion; I'll try to think of something that can explain this in a slightly broader way than "just" loimpress import (which I'm assuming you selected because that is where you expect the majority of your users to be coming from).

**Comment by aspiers** [comment]
Exactly right - that's why I didn't simply submit this as a PR to you directly; the LO use case is more applicable in our environment.
