### ISSUE TITLE
support for shellinabox?

### ISSUE THREAD

**Issue by aspiers** [fghaas/presentation-template#8]
Similarly to #6, probably worth providing out-of-the-box support for shellinabox.

**Comment by fghaas** [comment]
Shellinabox has no JS/CSS dependencies at all, the way to include it is just to add an iframe. I'm also a little reluctant to add shellinaboxd itself as a submodule, because it requires compiling locally and I'd generally recommend that people just install packages.

Or are you suggesting I simply add my wrapper script?

**Comment by aspiers** [comment]
As with asciinema, I'm a total ignoramus regarding how this is set up, so this request may not make sense.  What does your wrapper script do?

**Comment by fghaas** [comment]
I'll try to get this wrapped up and included in the repo over the weekend.
